"""rename phone number column

Revision ID: 1aa9c35db96c
Revises: 474dced51acf
Create Date: 2024-02-15 20:10:47.699483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa9c35db96c'
down_revision: Union[str, None] = '474dced51acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'phone_numer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
